### PR TITLE
added date command

### PR DESCRIPTION
**Pull request by Dishebh**

### CODE REVIEW

**Review by imabp — APPROVED** [review]
Good work !

**Comment by imabp** [comment]
@Dishebh  your changes have been deployed to production,
Check here: 

https://imabp.github.io/WebTerminal/

**Comment by Dishebh** [comment]
Hi @imabp, thanks for letting me know :). But I get a 404 while opening the link. Can you please cross check it if it is deployed and live?

**Comment by imabp** [comment]
@Dishebh Sorry for that. 
I forgot to mention one thing, the  route is case sensitive
Correct route is: https://imabp.github.io/WebTerminal/

**Pull request merged**
